import requests
import json

# Define the Jira API URL
jira_api_url = "https://your-jira-instance.com/rest/api/2/issue/"

# Define the Jira credentials
username = "your-username"
password = "your-password"

# Define the Jira project key where the tickets will be created
project_key = "YOUR-PROJECT-KEY"

# Define the function to submit Jira tickets
def submit_jira_ticket(ticket_text):
    # Define the Jira ticket data
    data = {
        "fields": {
            "project": {
                "key": project_key
            },
            "summary": ticket_text,
            "description": ticket_text,
            "issuetype": {
                "name": "Task"
            }
        }
    }

    # Send the HTTP POST request to create the Jira ticket
    response = requests.post(jira_api_url, auth=(username, password), headers={"Content-Type": "application/json"}, data=json.dumps(data))

    # Check the response status code
    if response.status_code == 201:
        print("Jira ticket submitted successfully!")
    else:
        print("Error submitting Jira ticket: " + str(response.content))

# Test the Jira submission function
submit_jira_ticket("This is a test ticket generated by the AI platform.")
